eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8988/eurekaServer/eureka/
server:
  port: 8984
spring:
  application:
    name: service-feign

# feign自带断路器,,默认关闭
feign:
  hystrix:
    enabled: true
