server:
  port: 8987
  servlet:
    context-path: /eurekaClient/
spring:
  application:
    name: eureka-client
  #配置zipkin server地址
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    service-url:
      defaultZone: http://peer1:8977/eurekaServer/eureka/
  #配置这个将空页面status状态会显示IP而不是主机名  但是测试没有生效...
  instance:
      prefer-ip-address: true

#添加如下配置才能请求到页面 http://localhost:8987/eurekaClient/actuator/hystrix.stream
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"



