server:
  port: 8986
  servlet:
    context-path: /eurekaClient/
spring:
  application:
    name: eureka-client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8988/eurekaServer/eureka/

