server:
  port: 8971
spring:
  application:
    name: service-turbine
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8977/eurekaServer/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
turbine:
  app-config: eureka-client,eureka-client2
  aggregator:
    cluster-config: default
  cluster-name-expression: new String("default")
  combine-host: true
  instanceUrlSuffix:
     default: actuator/hystrix.stream